route:
  receiver: blackhole
  routes:
    - match:
        alertname: ZFSPoolIsFailing
      receiver: email
    - match:
        alertname: SystemdUnitFailed
      receiver: email
      repeat: '1h'

receivers:
  - name: blackhole

  - name: email
    email_configs:
      - to: "$SMTP_EMAIL_TO"
        from: "$SMTP_EMAIL_FROM"
        smarthost: "$SMTP_SMART_HOST"
        auth_username: "$SMTP_USERNAME"
        auth_password: "$SMTP_PASSWORD"
