route:
  receiver: blackhole

receivers:
  - name: email
    email_configs:
      - to: "$SMTP_EMAIL_TO"
        from: "$SMTP_EMAIL_FROM"
        smarthost: "$SMTP_SMART_HOST"
        auth_username: "$SMTP_USERNAME"
        auth_password: "$SMTP_PASSWORD"
