route:
  receiver: blackhole
  group_by: ["alertname", "job"]
  routes:
    - match:
        alertname: ZFSPoolIsFailing
      receiver: email
    - match:
        alertname: SystemdUnitFailed
      receiver: email
      repeat_interval: '1h'
    - match:
        alertname: ToastyHardDisks
      receiver: email
      repeat_interval: '1h'
    - match:
        alertname: BurntHardDisks
      receiver: email
      repeat_interval: '1h'
    - match:
        alertname: ReallocatingSectors
      receiver: email
      repeat_interval: '6h'

receivers:
  - name: blackhole

  - name: email
    email_configs:
      - to: "$SMTP_EMAIL_TO"
        from: "$SMTP_EMAIL_FROM"
        smarthost: "$SMTP_SMART_HOST"
        auth_username: "$SMTP_USERNAME"
        auth_password: "$SMTP_PASSWORD"
