{
 "title": "ZFS",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(zpool_stats_size, instance)"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "label_values(zpool_stats_size{instance=\"$instance\", vdev=\"root\"}, name)"
    }
   },
   {
    "name": "vdev",
    "label": "VDEV",
    "query": {
     "query": "label_values(zpool_stats_size{instance=\"$instance\", name=~\"$pool\", vdev!~\"root\", path=\"\"}, vdev)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Zpool stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Zpool",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "zpool_stats_size{instance=\"$instance\",name=~\"$pool\",vdev=~\"root\"}",
       "legendFormat": "size"
      },
      {
       "expr": "zpool_stats_alloc{instance=\"$instance\",name=~\"$pool\",vdev=~\"root\"}",
       "legendFormat": "alloc"
      },
      {
       "expr": "zpool_stats_free{instance=\"$instance\",name=~\"$pool\",vdev=~\"root\"}",
       "legendFormat": "free"
      },
      {
       "expr": "(zpool_stats_alloc{instance=\"$instance\",name=~\"$pool\",vdev=~\"root\"} /\nzpool_stats_size{instance=\"$instance\",name=~\"$pool\",vdev=~\"root\"}) * 100",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Read Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_read_bytes{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Write Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_write_bytes{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Read Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_read_ops{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Write Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_write_ops{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Read Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_read_errors{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Write Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_write_errors{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "VDEV stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "VDEV",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "zpool_stats_size{instance=\"$instance\",name=~\"$pool\",vdev=~\"$vdev\"}",
       "legendFormat": "size"
      },
      {
       "expr": "zpool_stats_alloc{instance=\"$instance\",name=~\"$pool\",vdev=~\"$vdev\"}",
       "legendFormat": "alloc"
      },
      {
       "expr": "zpool_stats_free{instance=\"$instance\",name=~\"$pool\",vdev=~\"$vdev\"}",
       "legendFormat": "free"
      },
      {
       "expr": "(zpool_stats_alloc{instance=\"$instance\",name=~\"$pool\",vdev=~\"$vdev\"} /\nzpool_stats_size{instance=\"$instance\",name=~\"$pool\",vdev=~\"$vdev\"}) * 100",
       "legendFormat": "capacity"
      },
      {
       "expr": "zpool_stats_fragmentation{instance=\"$instance\",name=~\"$pool\",vdev=\"$vdev\"}",
       "legendFormat": "fragmentation"
      }
     ]
    },
    {
     "title": "Read Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_read_bytes{instance=\"$instance\",name=~\"$pool\",vdev=~\"$vdev\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }} - {{ vdev }}"
      }
     ]
    },
    {
     "title": "Write Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_write_bytes{instance=\"$instance\",name=~\"$pool\",vdev=~\"$vdev\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }} - {{ vdev }}"
      }
     ]
    },
    {
     "title": "Read Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_read_ops{instance=\"$instance\",name=~\"$pool\",vdev=~\"$vdev\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }} - {{ vdev }}"
      }
     ]
    },
    {
     "title": "Write Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_write_ops{instance=\"$instance\",name=~\"$pool\",vdev=~\"$vdev\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }} - {{ vdev }}"
      }
     ]
    },
    {
     "title": "Read Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_read_errors{instance=\"$instance\",name=~\"$pool\",vdev=~\"$vdev\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }} - {{ vdev }}"
      }
     ]
    },
    {
     "title": "Write Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_write_errors{instance=\"$instance\",name=~\"$pool\",vdev=~\"$vdev\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }} - {{ vdev }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volumes",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "zpool_stats_fragmentation{instance=\"$instance\",name=~\"$pool\",vdev!=\"root\",path!=\"\"}",
       "legendFormat": "fragmentation"
      },
      {
       "expr": "zpool_stats_checksum_errors{instance=\"$instance\",name=~\"$pool\",vdev!=\"root\",path!=\"\"}",
       "legendFormat": "checksum errors"
      }
     ]
    },
    {
     "title": "Read Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_read_bytes{instance=\"$instance\",name=~\"$pool\",path!=\"\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }} - {{ vdev }}"
      }
     ]
    },
    {
     "title": "Write Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_write_bytes{instance=\"$instance\",name=~\"$pool\",path!=\"\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }} - {{ vdev }}"
      }
     ]
    },
    {
     "title": "Read Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_read_ops{instance=\"$instance\",name=~\"$pool\",path!=\"\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }} - {{ vdev }}"
      }
     ]
    },
    {
     "title": "Write Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_write_ops{instance=\"$instance\",name=~\"$pool\",path!=\"\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }} - {{ vdev }}"
      }
     ]
    },
    {
     "title": "Read Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_read_errors{instance=\"$instance\",name=~\"$pool\",path!=\"\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }} - {{ vdev }}"
      }
     ]
    },
    {
     "title": "Write Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(zpool_stats_write_errors{instance=\"$instance\",name=~\"$pool\",path!=\"\"}[$__rate_interval])) without (state)",
       "legendFormat": "{{ name }} - {{ vdev }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Finished",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "zpool_scan_stats_start_ts{instance=\"$instance\",name=~\"$pool\",state=\"finished\"} * 1000",
       "legendFormat": "start time"
      },
      {
       "expr": "zpool_scan_stats_end_ts{instance=\"$instance\",name=~\"$pool\",state=\"finished\"} * 1000",
       "legendFormat": "end time"
      },
      {
       "expr": "zpool_scan_stats_examined{instance=\"$instance\",name=~\"$pool\",state=\"finished\"}",
       "legendFormat": "scaned"
      },
      {
       "expr": "zpool_scan_stats_processed{instance=\"$instance\",name=~\"$pool\",state=\"finished\"}",
       "legendFormat": "repaired"
      },
      {
       "expr": "zpool_scan_stats_errors{instance=\"$instance\",name=~\"$pool\",state=\"finished\"}",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Ongoing",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "zpool_scan_stats_start_ts{instance=\"$instance\",name=~\"$pool\",state!=\"finished\"} * 1000",
       "legendFormat": "start time"
      },
      {
       "expr": "zpool_scan_stats_rate{instance=\"$instance\",name=~\"$pool\",state!=\"finished\"}",
       "legendFormat": "rate"
      },
      {
       "expr": "zpool_scan_stats_errors{instance=\"$instance\",name=~\"$pool\",state!=\"finished\"}",
       "legendFormat": "errors"
      },
      {
       "expr": "zpool_scan_stats_to_examine{instance=\"$instance\",name=~\"$pool\",state!=\"finished\"}",
       "legendFormat": "to scan"
      },
      {
       "expr": "zpool_scan_stats_to_process{instance=\"$instance\",name=~\"$pool\",state!=\"finished\"}",
       "legendFormat": "to repair"
      }
     ]
    },
    {
     "title": "Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "zpool_scan_stats_rate{instance=\"$instance\",name=~\"$pool\",state!=\"finished\"}",
       "legendFormat": "{{ name }} - {{ function }}"
      }
     ]
    }
   ]
  },
  {
   "title": "ARC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "ARC size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "zfs_arcstats_size{instance=\"$instance\"}",
       "legendFormat": "actual"
      },
      {
       "expr": "zfs_arcstats_c{instance=\"$instance\"}",
       "legendFormat": "target"
      },
      {
       "expr": "zfs_arcstats_data_size{instance=\"$instance\"}",
       "legendFormat": "data"
      },
      {
       "expr": "zfs_arcstats_metadata_size{instance=\"$instance\"}",
       "legendFormat": "metadata"
      }
     ]
    },
    {
     "title": "ARC - hit %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(zfs_arcstats_demand_data_hits{instance=\"$instance\"}[$__rate_interval]) /\n(\nrate(zfs_arcstats_demand_data_hits{instance=\"$instance\"}[$__rate_interval]) +\nrate(zfs_arcstats_demand_data_misses{instance=\"$instance\"}[$__rate_interval])\n) * 100",
       "legendFormat": "data"
      },
      {
       "expr": "rate(zfs_arcstats_demand_metadata_hits{instance=\"$instance\"}[$__rate_interval]) /\n(\nrate(zfs_arcstats_demand_metadata_hits{instance=\"$instance\"}[$__rate_interval]) +\nrate(zfs_arcstats_demand_metadata_misses{instance=\"$instance\"}[$__rate_interval])\n) * 100",
       "legendFormat": "metadata"
      }
     ]
    },
    {
     "title": "MRU",
     "type": "timeseries",
     "description": "Most Recently Used cache",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(zfs_arcstats_mru_hits{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "hits"
      },
      {
       "expr": "rate(zfs_arcstats_mru_ghost_hits{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "ghost hits"
      }
     ]
    },
    {
     "title": "MFU",
     "type": "timeseries",
     "description": "Most Frequently Used cache",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(zfs_arcstats_mfu_hits{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "hits"
      },
      {
       "expr": "rate(zfs_arcstats_mfu_ghost_hits{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "ghost hits"
      }
     ]
    }
   ]
  },
  {
   "title": "L2 ARC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "L2 ARC size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "zfs_arcstats_l2_size{instance=\"$instance\"}",
       "legendFormat": "actual"
      },
      {
       "expr": "zfs_arcstats_l2_hdr_size{instance=\"$instance\"}",
       "legendFormat": "hdr"
      }
     ]
    },
    {
     "title": "ARC - hit %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(zfs_arcstats_l2_hits{instance=\"$instance\"}[$__rate_interval]) /\n(\nrate(zfs_arcstats_l2_hits{instance=\"$instance\"}[$__rate_interval]) +\nrate(zfs_arcstats_l2_misses{instance=\"$instance\"}[$__rate_interval])\n) * 100",
       "legendFormat": "hit"
      }
     ]
    }
   ]
  },
  {
   "title": "IO size - $pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "pool",
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Read",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(zpool_io_size_sync_read_ind{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Sync Write",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(zpool_io_size_sync_write_ind{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Async Read",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(zpool_io_size_async_read_ind{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Async Write",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(zpool_io_size_async_write_ind{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Scrub",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(zpool_io_size_scrub_read_ind{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Trim",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(zpool_io_size_trim_write_ind{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency - $pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "pool",
   "collapsed": true,
   "panels": [
    {
     "title": "Total Read Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_total_read{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Total Write Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_total_read{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Disk Read Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_disk_read{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Disk Write Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_disk_write{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Sync Read Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_sync_read{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Sync Write Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_sync_write{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Async Read Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_async_read{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Async Write Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_async_write{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Scrub",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_scrub{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Trim",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_trim{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ pool }}"
      }
     ]
    }
   ]
  },
  {
   "title": "ZIO queue - $pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "pool",
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "zpool_vdev_queue_sync_r_active{instance=\"$instance\",name=\"$pool\"}",
       "legendFormat": "active"
      },
      {
       "expr": "zpool_vdev_queue_sync_r_pend{instance=\"$instance\",name=\"$pool\"}",
       "legendFormat": "pending"
      }
     ]
    },
    {
     "title": "Sync Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "zpool_vdev_queue_sync_w_active{instance=\"$instance\",name=\"$pool\"}",
       "legendFormat": "active"
      },
      {
       "expr": "zpool_vdev_queue_sync_w_pend{instance=\"$instance\",name=\"$pool\"}",
       "legendFormat": "pending"
      }
     ]
    },
    {
     "title": "Async Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "zpool_vdev_queue_async_r_active{instance=\"$instance\",name=\"$pool\"}",
       "legendFormat": "active"
      },
      {
       "expr": "zpool_vdev_queue_async_r_pend{instance=\"$instance\",name=\"$pool\"}",
       "legendFormat": "pending"
      }
     ]
    },
    {
     "title": "Async Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "zpool_vdev_queue_async_w_active{instance=\"$instance\",name=\"$pool\"}",
       "legendFormat": "active"
      },
      {
       "expr": "zpool_vdev_queue_async_w_pend{instance=\"$instance\",name=\"$pool\"}",
       "legendFormat": "pending"
      }
     ]
    },
    {
     "title": "Scrub",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "zpool_vdev_queue_async_scrub_active{instance=\"$instance\",name=\"$pool\"}",
       "legendFormat": "active"
      },
      {
       "expr": "zpool_vdev_queue_async_scrub_pend{instance=\"$instance\",name=\"$pool\"}",
       "legendFormat": "pending"
      }
     ]
    }
   ]
  }
 ]
}